kind: pipeline
type: docker
name: drone-runner-1

platform:
  os: linux
  arch: arm

steps:
  - name: test
    image: node
    commands:
      - npm install
      - npm test
  - name: publish
    image: docker:stable-dind
    commands:
      - docker build .
      - docker run -d
