kind: pipeline
type: docker
name: drone-runner-docker

platform:
  os: linux
  arch: arm

steps:
  - name: test
    image: node
    commands:
      - npm install
      - npm test
  - name: publish
    image: docker:stable-dind
    privileged: true
    commands:
      - docker build -t node-js-test:${DRONE_COMMIT_SHA} .
      - docker run --name node-js-test -p 8086:3000 -d node-js-test:${DRONE_COMMIT_SHA}
    volumes:
      - name: docker_run
        path: /var/run/
      - name: docker_lib
        path: /var/lib/docker
