kind: pipeline
type: docker

platform:
  os: linux

steps:
  - name: test
    image: node
    commands:
      - npm install
      - npm test
  - name: publish
    image: docker:stable-dind
    commands:
      - docker build .
      - docker run -d
