kind: pipeline
type: docker
name: default

steps:
  - name: test
      image: node
      commands:
        - npm install
        - npm test
  - name: publish
      image: docker:stable-dind
      commands:
        - docker build .
        - docker run -d
